markdown: kramdown
highlighter: rouge
permalink: /blog/:title
rdiscount:
  extensions: [smart]
defaults:
  -
    values:
      layout: cssday
exclude:
  - .gitignore
  - dustman.yml
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - README.md

conf:
  cfp_url: https://goo.gl/forms/NpVU3q7xmcSaspsJ2
  cfp: true
  cfs: true
  full_date: "Faenza (RA),  17 marzo 2017"
  media_tags: "faenza"
  name: PHP day
  og_image:
  og_title:
  og_url: http://2016.cssday.it
  speakers: false
  theme: phpday
  tickets_url: //eventbrite.com/tickets-external?eid=28891550405
  tickets: true
  where: faenza-sarti
  year: 2017
