
markdown: kramdown
highlighter: rouge
permalink: /blog/:title
rdiscount:
  extensions: [smart]
defaults:
  -
    values:
      layout: phpday
exclude:
  - .gitignore
  - dustman.yml
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - README.md
